import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import pg from "pg";
import {
  executableStatements,
  normalizeLead,
  requireId,
  statementsForLead,
  validateScoreInvariant,
  type LeadIn,
} from "../services/agent-mcp/src/postgres/leadgen-enrichment-sql.ts";

/**
 * Turn enrichment JSON into idempotent SQL — or apply directly to Postgres.
 *
 *   npx tsx scripts/leadgen-apply-enrichment.ts tmp/enrichment-<runId>.json --run-id <id> --out tmp/out.sql
 *   npx tsx scripts/leadgen-apply-enrichment.ts tmp/enrichment-<runId>.json --run-id <id> --apply
 *   npx tsx scripts/leadgen-apply-enrichment.ts tmp/scores.json --scores-only --apply
 *
 * --apply: one transaction per lead (default --chunk 1). Uses DATABASE_URL or LEADGEN_DATABASE_URL.
 * Prefer Postgres MCP upsert_lead_enrichment from cloud agents; --apply is for local/CI.
 *
 * MCP fallback (deprecated for writes): --out + execute comments one statement at a time, never >8 KB.
 */
const { Pool } = pg;

function usage(message?: string): never {
  if (message) console.error(message);
  console.error(
    "Usage: npx tsx scripts/leadgen-apply-enrichment.ts <file.json> " +
      "[--run-id ID] [--chunk N] [--check] [--scores-only] [--apply] [--database-url URL] [--out file.sql]",
  );
  process.exit(1);
}

function parseArgs(argv: string[]) {
  const flags: Record<string, string | boolean> = {};
  const rest: string[] = [];
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--check") flags.check = true;
    else if (arg === "--scores-only") flags["scores-only"] = true;
    else if (arg === "--apply") flags.apply = true;
    else if (arg === "--run-id" || arg === "--chunk" || arg === "--out" || arg === "--database-url") {
      const next = argv[++i];
      if (!next) usage(`Missing value for ${arg}`);
      flags[arg.slice(2)] = next;
    } else if (arg.startsWith("-")) usage(`Unknown flag ${arg}`);
    else rest.push(arg);
  }
  return { file: rest[0], flags };
}

async function applyLead(pool: pg.Pool, lead: LeadIn, runId: string | null, scoresOnly: boolean): Promise<void> {
  const stmts = executableStatements(statementsForLead(lead, runId, scoresOnly));
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    for (const stmt of stmts) {
      await client.query(stmt);
    }
    await client.query("COMMIT");
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

async function main() {
  const { file, flags } = parseArgs(process.argv.slice(2));
  if (!file) usage();
  const runId = typeof flags["run-id"] === "string" ? requireId(flags["run-id"], "run-id") : null;
  const apply = flags.apply === true;
  const scoresOnly = flags["scores-only"] === true;
  const defaultChunk = apply ? 1 : 10;
  const chunkSize = Number(flags.chunk ?? defaultChunk);
  if (!Number.isInteger(chunkSize) || chunkSize < 1) usage("--chunk must be a positive integer");

  const parsed = JSON.parse(readFileSync(resolve(file), "utf8"));
  const rows: LeadIn[] = Array.isArray(parsed) ? parsed : parsed.leads;
  if (!Array.isArray(rows)) usage("JSON must be an array of leads or { leads: [] }");

  const leads = rows.map(normalizeLead);
  for (const lead of leads) {
    validateScoreInvariant(lead, scoresOnly);
  }
  if (flags.check) {
    console.log(`OK ${leads.length} leads`);
    return;
  }

  if (apply) {
    const databaseUrl =
      (typeof flags["database-url"] === "string" ? flags["database-url"] : null) ??
      process.env.LEADGEN_DATABASE_URL ??
      process.env.DATABASE_URL;
    if (!databaseUrl) {
      usage("--apply requires DATABASE_URL, LEADGEN_DATABASE_URL, or --database-url");
    }
    const pool = new Pool({ connectionString: databaseUrl });
    let applied = 0;
    const errors: { ico: string; error: string }[] = [];
    try {
      for (const lead of leads) {
        try {
          await applyLead(pool, lead, runId, scoresOnly);
          applied++;
          console.error(`applied ${lead.ico} (${applied}/${leads.length})`);
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error);
          errors.push({ ico: lead.ico, error: message });
          console.error(`FAILED ${lead.ico}: ${message}`);
        }
      }
    } finally {
      await pool.end();
    }
    console.log(JSON.stringify({ applied, failed: errors.length, errors }, null, 2));
    if (errors.length > 0) process.exit(1);
    return;
  }

  const header = [
    "-- generated by scripts/leadgen-apply-enrichment.ts",
    `-- source ${file}`,
    `-- leads ${leads.length}`,
    runId ? `-- AgentRun ${runId}` : "-- no AgentRun id",
    scoresOnly ? "-- scores-only backfill" : "-- One statement per MCP query. Never bundle >8 KB.",
  ];
  const body: string[] = [];
  leads.forEach((lead, i) => {
    if (i % chunkSize === 0) {
      body.push(
        `-- MCP CHUNK ${Math.floor(i / chunkSize) + 1} (leads ${i + 1}-${Math.min(i + chunkSize, leads.length)})`,
      );
    }
    body.push(...statementsForLead(lead, runId, scoresOnly));
  });
  const sql = [...header, ...body, ""].join("\n");

  if (typeof flags.out === "string") {
    writeFileSync(resolve(flags.out), sql);
    console.error(`Wrote ${flags.out} (${leads.length} leads)`);
  } else {
    process.stdout.write(sql);
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
